// User
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const DESTROY_SESSION = "DESTROY_SESSION";
export const SET_TOKENS = "SET_TOKENS";
export const SET_USER_DATA = "SET_USER_DATA";

//New Volunteer
export const ADD_PERSON = "ADD_PERSON";
export const ADD_VOLUNTEER = "ADD_VOLUNTEER";
export const ADD_VOLUNTEER_AVAILABILITY = "ADD_VOLUNTEER_AVAILABILITY";
export const ADD_EMERGENCY_CONTACT = "ADD_EMERGENCY_CONTACT";
export const DELETE_DATA = "DELETE_DATA";

// Departments
export const GET_DEPARTMENTS = "GET_DEPARTMENTS";

//Volunteer
export const SET_VOLUNTEERS = "SET_VOLUNTEERS";
export const SET_SELECTED_PERSON = "SET_SELECTED_PERSON";
export const SET_SELECTED_VOLUNTEER = "SET_SELECTED_VOLUNTEER";
export const SET_SELECTED_VOLUNTEER_AVAILABILITY =
  "SET_SELECTED_VOLUNTEER_AVAILABILITY";
export const SET_SELECTED_EMERGENCY_CONTACT = "SET_SELECTED_EMERGENCY_CONTACT";

//Company
export const SET_COMPANIES = "SET_COMPANIES";

//Market
export const SET_MARKETS = "SET_MARKETS";

//ProductCategory
export const SET_PRODUCT_CATEGORIES = "SET_PRODUCT_CATEGORIES";

//Events
export const SET_ALL_EVENTS = "SET_ALL_EVENTS";
export const SET_VOLUNTEER_EVENTS = "SET_VOLUNTEER_EVENTS";

//New Beneficiary
export const ADD_BENEFICIARY_PERSON = "ADD_BENEFICIARY_PERSON";
export const ADD_BENEFICIARY_FAMILY = "ADD_BENEFICIARY_FAMILY";
export const ADD_BENEFICIARY_FAMILY_MEMBER = "ADD_BENEFICIARY_FAMILY_MEMBER";
export const UPDATE_BENEFICIARY_FAMILY_MEMBER =
  "UPDATE_BENEFICIARY_FAMILY_MEMBER";
export const DELETE_BENEFICIARY_FAMILY_MEMBER =
  "DELETE_BENEFICIARY_FAMILY_MEMBER";

//Beneficiary Organizations
export const SET_BENEFICIARY_ORGANIZATIONS = "SET_BENEFICIARY_ORGANIZATIONS";

//Trip
export const SET_TRIPS = "SET_TRIPS";

//Tranport
export const SET_SELECTED_TRANSPORT_REQUEST = "SET_SELECTED_TRANSPORT_REQUEST";
